version: '3.8'

services:
  php:
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/var/www

  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/var/www
      - .docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
      - .docker/nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - php

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    volumes:
      - ./docker/db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: nt
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: laravel

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: nata.mark140895@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tulidu140895@
    depends_on:
      - db
